### ISSUE TITLE
stopped working (api issue)

### ISSUE THREAD

**Issue by PeanutAria** [Spicadox/auto-twitter-space#6] opened 2023-06-13 19:31 UTC
i just found out that it stopped working. there's an error saying
```
403 Forbiddenve twitter spaces .
When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.
```

when i looked at my twitter developer portal, i no longer can see the details of the project that i created for this app and there's no space lookup for free tier.

![2023-06-14 03_17_38-Twitter_Developers_—_Waterfox](https://github.com/Spicadox/auto-twitter-space/assets/121492287/909b07d0-ba4f-4d62-a2f6-e1a74710152f)

i saw that you've created a dev branch, space bot v2 that uses guest token, i've tried to use the v2, but unfortunately it doesn't work.

got an error , it's about `const.ALL_SPACE_TIMELINE`. i don't know what it's for, so i just delete the line for that and run it again.

found some random user that's currently live and the log just said
```
2023-06-14 02:53:26 [twitter_space_bot_v2.py:427] INFO     Starting program
2023-06-14 02:53:26 [twitter_space_bot_v2.py:95] DEBUG    Guest Token Response: <Response [200]>
2023-06-14 02:53:26 [twitter_space_bot_v2.py:98] DEBUG    Renewed Guest Token: 1668693141803929601
2023-06-14 02:53:27 [twitter_space_bot_v2.py:193] DEBUG    Space ID for ConsultingNaz(1356907079420833792): 1yoKMZaeqQzGQ
```
and it keeps repeating the 4th line over and over.

**Comment by Spicadox** [comment] 2023-06-13 21:23
Yep, the script was basically dead since it doesn't work on the free tier and just for my own purposes I decided to rework the script that'll work using the guest tokens as you've noticed in the dev branch.

The error with `const.ALL_SPACE_TIMELINE` has been fixed because the const.py file was not updated. FYI as of now it doesn't do anything so even if you remove it completely, it wouldn't matter either way.

I'm still working on it at a snail's pace but as of now it's working on my machine and I've pushed all the latest changes, so for now, if you don't mind pulling these new changes and see if it works.

**Comment by PeanutAria** [comment] 2023-06-14 02:16
found a live space and it works. thank you😊 i will let you know again after the live has ended to make sure everything's working fine

**Comment by PeanutAria** [comment] 2023-06-14 06:25
so, at first i thought there's something wrong because it doesn't download the live, but it turns out that maybe because i didn't install `dataclasses`.

after installing it and finding another live space, it downloaded just fine, but after it finished, error comes, and it says:
```
2023-06-14 13:17:56 [twitter_space_bot_v2.py:428] INFO     StuffKSaid is now offline at 1OdKrzWrjNQKX
2023-06-14 13:17:56 [twitter_space_bot_v2.py:443] ERROR    expected string or bytes-like object, got 'NoneType'
Traceback (most recent call last):
  File "B:\!monitoring tools\auto-twitter-space (dev)\twitter_space_bot_v2.py", line 432, in download
    server = ended_space.get_server()
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "B:\!monitoring tools\auto-twitter-space (dev)\TwitterSpace.py", line 35, in get_server
    reg_result = re.search("(https:\/\/)((?:[^-]*-){2})(.*)(\.pscp.*)", self.m3u8_url)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 176, in search
    return _compile(pattern, flags).search(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```
here's the log, i edited to make it short and easy, the full log has almost 60k line
[logfile (edited).log](https://github.com/Spicadox/auto-twitter-space/files/11742303/logfile.edited.log)

i don't know what the log file would look like if there's multiple user in the monitoring list, there's only 1 user for testing, so it'd be easy for me to read the log, but i can try testing it with multiple user if you want.

**Comment by PeanutAria** [comment] 2023-06-14 12:44
i don't know what happened but after trying it again with my throwaway account, everything's working fine. no error.

all i did was remove `space_creator` in `twspace.py line 76 & 79` because i like all the downloaded space in 1 folder instead of multiple subfolder. and updated ffmpeg to version 2023-06-11-git-09621fd7d9

but there's another problem when the host doesn't put any title whist creating a space. it won't catch(?) the live space, instead it keeps repeating `Issue getting latest space id` over and over.
```
2023-06-14 20:39:04 [twitter_space_bot_v2.py:406] ERROR    [FfyDh95583] Issue getting latest space id
Traceback (most recent call last):
  File "B:\!monitoring tools\auto-twitter-space (dev)\twitter_space_bot_v2.py", line 400, in get_spaces
    user.set_space_details(space_details)
  File "B:\!monitoring tools\auto-twitter-space (dev)\TwitterSpace.py", line 53, in set_space_details
    self.space_title = space_details['title']
                       ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'title'
```

[logfile (throwaway error).log](https://github.com/Spicadox/auto-twitter-space/files/11745831/logfile.throwaway.error.log)

**Comment by Spicadox** [comment] 2023-06-14 13:53
> so, at first i thought there's something wrong because it doesn't download the live, but it turns out that maybe because i didn't install `dataclasses`.
> 
> after installing it and finding another live space, it downloaded just fine, but after it finished, error comes, and it says:
> 
> ```
> 2023-06-14 13:17:56 [twitter_space_bot_v2.py:428] INFO     StuffKSaid is now offline at 1OdKrzWrjNQKX
> 2023-06-14 13:17:56 [twitter_space_bot_v2.py:443] ERROR    expected string or bytes-like object, got 'NoneType'
> Traceback (most recent call last):
>   File "B:\!monitoring tools\auto-twitter-space (dev)\twitter_space_bot_v2.py", line 432, in download
>     server = ended_space.get_server()
>              ^^^^^^^^^^^^^^^^^^^^^^^^
>   File "B:\!monitoring tools\auto-twitter-space (dev)\TwitterSpace.py", line 35, in get_server
>     reg_result = re.search("(https:\/\/)((?:[^-]*-){2})(.*)(\.pscp.*)", self.m3u8_url)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\user\AppData\Local\Programs\Python\Python311\Lib\re\__init__.py", line 176, in search
>     return _compile(pattern, flags).search(string)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> TypeError: expected string or bytes-like object, got 'NoneType'
> ```
> 
> here's the log, i edited to make it short and easy, the full log has almost 60k line [logfile (edited).log](https://github.com/Spicadox/auto-twitter-space/files/11742303/logfile.edited.log)
> 
> i don't know what the log file would look like if there's multiple user in the monitoring list, there's only 1 user for testing, so it'd be easy for me to read the log, but i can try testing it with multiple user if you want.

I'm seeing in the log that intially the space 1OdKrzWrjNQKX ended and the download was successful the first time around, but is failing the second time. Though I gotta wonder why the space id is the same the second time around as the id should be unique 🤔.

The issue is because the script was getting 404 error(never gotten this error?) when trying to get the m3u8 url to initiate the download. For now, I've just made sure that if the m3u8 url isn't found then the script will try a few more times to try and get it, but otherwise, if the attempt fails, an error will be logged and you'll have to manually get the m3u8 url and download it.

**Comment by Spicadox** [comment] 2023-06-14 14:04
> i don't know what happened but after trying it again with my throwaway account, everything's working fine. no error.
> 
> all i did was remove `space_creator` in `twspace.py line 76 & 79` because i like all the downloaded space in 1 folder instead of multiple subfolder. and updated ffmpeg to version 2023-06-11-git-09621fd7d9
> 
> but there's another problem when the host doesn't put any title whist creating a space. it won't catch(?) the live space, instead it keeps repeating `Issue getting latest space id` over and over.
> 
> ```
> 2023-06-14 20:39:04 [twitter_space_bot_v2.py:406] ERROR    [FfyDh95583] Issue getting latest space id
> Traceback (most recent call last):
>   File "B:\!monitoring tools\auto-twitter-space (dev)\twitter_space_bot_v2.py", line 400, in get_spaces
>     user.set_space_details(space_details)
>   File "B:\!monitoring tools\auto-twitter-space (dev)\TwitterSpace.py", line 53, in set_space_details
>     self.space_title = space_details['title']
>                        ~~~~~~~~~~~~~^^^^^^^^^
> KeyError: 'title'
> ```
> 
> [logfile (throwaway error).log](https://github.com/Spicadox/auto-twitter-space/files/11745831/logfile.throwaway.error.log)

Right, I'd initially had all downloads in one folder, but once I got to 100+ users spaces to monitor it got out of hand so I decided to further seperate download output location to it's corresponding space creator lol

Thanks, I didn't even realize the title for spaces aren't even required, so this is fixed now and I'll push out the changes later today.

**Comment by Spicadox** [comment] 2023-06-14 15:13
Latest changes have been pushed to dev. Please confirm that the issues have been resolved!

**Closed** 2023-06-14 16:07 UTC
